name: Npm Publish

on:
  push:
    branches:
      - dev

jobs:
  publish:
    if: "contains(github.event.head_commit.message, 'release')"
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16.x]
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Gen npmrc
        run: |
          echo "@jhqn:registry=https://registry.npmjs.com/" >> ./.npmrc
          echo "//registry.npmjs.com/:_authToken=${{ secrets.NPM_PUBLISH_TOKEN }}" >> ./.npmrc

      - name: Build & Publish
        run: npm run build && npm run release
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}
          REGISTRY: https://registry.npmjs.com/
